# Generated by Django 3.1.3 on 2020-11-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_store', '0002_category_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='category',
            new_name='categories',
        ),
    ]
