# Generated by Django 3.1.3 on 2020-11-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_store', '0003_auto_20201122_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='categories',
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_store.category'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='photo',
            field=models.ImageField(upload_to='sales/photos/'),
        ),
    ]
